### ISSUE TITLE
improper fork?

### ISSUE THREAD

**Issue by JazzMaster** [armornick/SDL_Draw#1]
mind you Im doing this in P but it seems the code you have here is already written(I misunderstood it) for accelerated rendering in the following units:

sdlsurface.inc
sdl2_gfx.pas
The included files from C are listed in the header defs.
Thank ev1313/Pascal-SDL-2-Headers

I could be wrong but it doesnt seem so.
Thank the dude here: https://www.freepascal-meets-sdl.net

Like I said, Im not a C expert here, but Id think that the C devs know this too. Theres two of you that forked this. One is for android and incomprehensible, the other is YOU.

-J

**Comment by armornick** [comment]
A few points to note:

* The code in this repository is very old code that I felt was in danger of disappearing off the internet. I haven't actually written a single line of the code in the repository myself.
* This library is for SDL version 1 whereas the code you point to is for SDL version 2, so they serve fairly different purposes.
